# Generated by Django 3.2.23 on 2023-12-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='related',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
