# Generated by Django 3.2.23 on 2023-12-18 08:01

from django.db import migrations, models

'''
We alter this field for the following reasons:
1)
2)
3)
'''

class Migration(migrations.Migration):

    dependencies = [
        ('dubai', '0002_testmodel_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='name',
            field=models.CharField(help_text='This is the name of our field', max_length=200),
        ),
    ]
