# Generated by Django 3.2.23 on 2023-12-18 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0088_auto_20231019_1244'),
        ('dubai', '0003_alter_testmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.resourcebase'),
        ),
    ]
